# Chapter 6: Analysis of longitudinal data 

*In this chapter, we will practice analysing longitudinal data.*

*After all these weeks of hard work, you should be able to go (almost) on your own. Please use the corresponding Exercise Set and the MABS4IODS materials: It should not be too difficult. Instead, it should be interesting and fun! (You should see NEW RESULTS that do NOT APPEAR in MABS!)*

*Note: As you read the data sets in your chapter6.Rmd you may have to factor the categorical variables again, as R may not recognise them automatically as factors.*

*Note that you must SWAP the data sets! :) It is NOT a simple copy & paste of the MABS book!*

*1. Implement the analyses of Chapter 8 of MABS, using the R codes of Exercise Set 6: Meet and Repeat: PART I but using the RATS data (from Chapter 9 and Meet and Repeat: PART II). (0-7 points: 0-4 points for graphs or analysis results + 0-3 points for their interpretations)*

*2. Implement the analyses of Chapter 9 of MABS, using the R codes of Exercise Set 6: Meet and Repeat: PART II, but using the BPRS data (from Chapter 8 and Meet and Repeat: PART I). (0-8 points: 0-4 points for graphs or analysis results + 0-4 points for their interpretations)*

BPRS data, in which 40 male subjects were randomly assigned to one of two treatment groups and each subject was rated on the brief psychiatric rating scale (BPRS) measured before treatment began (week 0) and then at weekly intervals for eight weeks. The BPRS assesses the level of 18 symptom constructs such as hostility, suspiciousness, hallucinations and grandiosity; each of these is rated from one (not present) to seven (extremely severe). The scale is used to evaluate patients suspected of having schizophrenia.

*Feel free with the graphs and analyses!*